<?php
/**
 * Created by PhpStorm.
 * User: wen
 * Date: 2018/4/22
 * Time: 12:22
 */

namespace app\models;


use yii\db\ActiveRecord;

class Address extends ActiveRecord
{
    public static function tableName(){
        return "{{%address}}";
    }

    public function rules()
    {
        return [
            [['userid','firstname','lastname','address','email','telephone']],
            [['createtime','postcode'],'safe'],
        ]; // TODO: Change the autogenerated stub
    }
}